### ISSUE TITLE
ubiContract calls returning empty

### ISSUE THREAD

**Issue by admirabilis** [michaelwoodson/goodtimes#1]
Hi! Thanks for this project! It has been working good for the last few weeks. Today, any `ubiContract` calls seem to be returning empty:

```
TypeError: Cannot read properties of null (reading 'toNumber')
    at /home/user/goodtimes/cli.js:43:85
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async claim (/home/user/goodtimes/cli.js:43:23)
    at async /home/user/goodtimes/cli.js:18:3
```

A quick Google search returns that the most common issue is a wrong ABI, but it was working fine before. Any ideas, please?

**Comment by michaelwoodson** [comment]
It looks like they moved the contract as part of the protocol upgrades for GoodDollarV2. I just pushed out a new version (1.0.6) pointing to the new address. I'll close this after I verify a claim tomorrow morning.

**Comment by admirabilis** [comment]
Worked for me, thank you very much! Since you have mentioned, will leave for you to close as you wish.

**Comment by michaelwoodson** [comment]
Worked for me too, thanks!
